### ISSUE TITLE
No License file, makes usage risky(er!)

### ISSUE THREAD

**Issue by Barney-x1** [Moderocky/Overlord#2]
Or at least, I couldn't find one. Potential users may be put off (I am!) by not being certain of whether they can utilise the library in their projects.

Obviously I would like to see a permissive license! MIT, BSD, Apache etc. If you don't want to apply any license but will allow people to use and modify the code as they wish, you need to state this in the Readme.

Thanks

**Comment by Moderocky** [comment]
This was shipped under the MIT licence.
I deliberately didn't include a licence file in the repository because I don't really want to encourage people to use this in production code (it's terminally unsafe!!)

You're absolutely fine to use it in any way you want, but I'd suggest using the code as an example, seeing how the thing you want works and writing your own version with proper safety for your project.

**Comment by Barney-x1** [comment]
Well, using Unsafe is not _necessarily_ any riskier than native code, which the JVM itself is full of. The deep cloning, for instance, is I think conceptually safe (though it needs modifying to avoid infinite recursion for circular references). The jailbreaking stuff is not intrinsically unsafe (though what you do with it might be).

However as long as you're happy for me to pillage from it then I'm happy! Thanks
